-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}

-- | Contains the default configuration
module GrocyClient.Configuration where

import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified GHC.Types 
import qualified GrocyClient.Common

-- | The default url specified by the OpenAPI specification
-- 
-- @xxx@
defaultURL = Data.Text.Internal.pack "xxx"
-- | The default application name used in the @User-Agent@ header which is based on the @info.title@ field of the specification
-- 
-- @Grocy REST API@
defaultApplicationName = Data.Text.Internal.pack "Grocy REST API"
-- | The default configuration containing the 'defaultURL' and no authorization
defaultConfiguration = GrocyClient.Common.Configuration defaultURL GrocyClient.Common.anonymousSecurityScheme GHC.Types.True defaultApplicationName
