-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation delete_files__group___fileName_
module GrocyClient.Operations.Delete_files__group___fileName_ where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > DELETE /files/{group}/{fileName}
-- 
-- Deletes the given file
delete_files__group___fileName_ :: forall m . GrocyClient.Common.MonadHTTP m => Delete_files__group___fileName_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Delete_files__group___fileName_Response) -- ^ Monadic computation which returns the result of the operation
delete_files__group___fileName_ parameters = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Delete_files__group___fileName_ResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_files__group___fileName_Response204
                                                                                                                                                                                                                                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Delete_files__group___fileName_Response400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Error400)
                                                                                                                                                                                                                                                        | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "DELETE") ("/files/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathGroup parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathFileName parameters))) Base.<> "")))) Base.mempty)
-- | Defines the object schema located at @paths.\/files\/{group}\/{fileName}.DELETE.parameters@ in the specification.
-- 
-- 
data Delete_files__group___fileName_Parameters = Delete_files__group___fileName_Parameters {
  -- | pathFileName: Represents the parameter named \'fileName\'
  -- 
  -- The file name (including extension)\<br>**BASE64 encoded**
  delete_files__group___fileName_ParametersPathFileName :: Data.Text.Internal.Text
  -- | pathGroup
  , delete_files__group___fileName_ParametersPathGroup :: FileGroups
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Delete_files__group___fileName_Parameters
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathFileName" Data.Aeson.Types.ToJSON..= delete_files__group___fileName_ParametersPathFileName obj] : ["pathGroup" Data.Aeson.Types.ToJSON..= delete_files__group___fileName_ParametersPathGroup obj] : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (["pathFileName" Data.Aeson.Types.ToJSON..= delete_files__group___fileName_ParametersPathFileName obj] : ["pathGroup" Data.Aeson.Types.ToJSON..= delete_files__group___fileName_ParametersPathGroup obj] : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Delete_files__group___fileName_Parameters
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Delete_files__group___fileName_Parameters" (\obj -> (Base.pure Delete_files__group___fileName_Parameters Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathFileName")) Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathGroup"))}
-- | Create a new 'Delete_files__group___fileName_Parameters' with all required fields.
mkDelete_files__group___fileName_Parameters :: Data.Text.Internal.Text -- ^ 'delete_files__group___fileName_ParametersPathFileName'
  -> FileGroups -- ^ 'delete_files__group___fileName_ParametersPathGroup'
  -> Delete_files__group___fileName_Parameters
mkDelete_files__group___fileName_Parameters delete_files__group___fileName_ParametersPathFileName delete_files__group___fileName_ParametersPathGroup = Delete_files__group___fileName_Parameters{delete_files__group___fileName_ParametersPathFileName = delete_files__group___fileName_ParametersPathFileName,
                                                                                                                                                                                                 delete_files__group___fileName_ParametersPathGroup = delete_files__group___fileName_ParametersPathGroup}
-- | Represents a response of the operation 'delete_files__group___fileName_'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Delete_files__group___fileName_ResponseError' is used.
data Delete_files__group___fileName_Response =
   Delete_files__group___fileName_ResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Delete_files__group___fileName_Response204 -- ^ The operation was successful
  | Delete_files__group___fileName_Response400 Error400 -- ^ The operation was not successful
  deriving (Show.Show, GHC.Classes.Eq)
-- | > DELETE /files/{group}/{fileName}
-- 
-- The same as 'delete_files__group___fileName_' but accepts an explicit configuration.
delete_files__group___fileName_WithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Delete_files__group___fileName_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Delete_files__group___fileName_Response) -- ^ Monadic computation which returns the result of the operation
delete_files__group___fileName_WithConfiguration config
                                                 parameters = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Delete_files__group___fileName_ResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_files__group___fileName_Response204
                                                                                                                                                                                                                                                                         | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Delete_files__group___fileName_Response400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Error400)
                                                                                                                                                                                                                                                                         | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "DELETE") ("/files/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathGroup parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathFileName parameters))) Base.<> "")))) Base.mempty)
-- | > DELETE /files/{group}/{fileName}
-- 
-- The same as 'delete_files__group___fileName_' but returns the raw 'Data.ByteString.ByteString'.
delete_files__group___fileName_Raw :: forall m . GrocyClient.Common.MonadHTTP m => Delete_files__group___fileName_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
delete_files__group___fileName_Raw parameters = Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "DELETE") ("/files/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathGroup parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathFileName parameters))) Base.<> "")))) Base.mempty)
-- | > DELETE /files/{group}/{fileName}
-- 
-- The same as 'delete_files__group___fileName_' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
delete_files__group___fileName_WithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Delete_files__group___fileName_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
delete_files__group___fileName_WithConfigurationRaw config
                                                    parameters = Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "DELETE") ("/files/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathGroup parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (delete_files__group___fileName_ParametersPathFileName parameters))) Base.<> "")))) Base.mempty)
