-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation get_objects__entity___objectId_
module GrocyClient.Operations.Get_objects__entity___objectId_ where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > GET /objects/{entity}/{objectId}
-- 
-- Returns a single object of the given entity
get_objects__entity___objectId_ :: forall m . GrocyClient.Common.MonadHTTP m => Get_objects__entity___objectId_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Get_objects__entity___objectId_Response) -- ^ Monadic computation which returns the result of the operation
get_objects__entity___objectId_ parameters = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Get_objects__entity___objectId_ResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Get_objects__entity___objectId_ResponseBody200Variants)
                                                                                                                                                                                                                                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Error400)
                                                                                                                                                                                                                                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response404 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Error400)
                                                                                                                                                                                                                                                        | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") ("/objects/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathEntity parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathObjectId parameters))) Base.<> "")))) Base.mempty)
-- | Defines the object schema located at @paths.\/objects\/{entity}\/{objectId}.GET.parameters@ in the specification.
-- 
-- 
data Get_objects__entity___objectId_Parameters = Get_objects__entity___objectId_Parameters {
  -- | pathEntity
  get_objects__entity___objectId_ParametersPathEntity :: ExposedEntity_NotIncludingNotListable
  -- | pathObjectId: Represents the parameter named \'objectId\'
  -- 
  -- A valid object id of the given entity
  , get_objects__entity___objectId_ParametersPathObjectId :: GHC.Types.Int
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_objects__entity___objectId_Parameters
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathEntity" Data.Aeson.Types.ToJSON..= get_objects__entity___objectId_ParametersPathEntity obj] : ["pathObjectId" Data.Aeson.Types.ToJSON..= get_objects__entity___objectId_ParametersPathObjectId obj] : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (["pathEntity" Data.Aeson.Types.ToJSON..= get_objects__entity___objectId_ParametersPathEntity obj] : ["pathObjectId" Data.Aeson.Types.ToJSON..= get_objects__entity___objectId_ParametersPathObjectId obj] : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Get_objects__entity___objectId_Parameters
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_objects__entity___objectId_Parameters" (\obj -> (Base.pure Get_objects__entity___objectId_Parameters Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathEntity")) Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathObjectId"))}
-- | Create a new 'Get_objects__entity___objectId_Parameters' with all required fields.
mkGet_objects__entity___objectId_Parameters :: ExposedEntity_NotIncludingNotListable -- ^ 'get_objects__entity___objectId_ParametersPathEntity'
  -> GHC.Types.Int -- ^ 'get_objects__entity___objectId_ParametersPathObjectId'
  -> Get_objects__entity___objectId_Parameters
mkGet_objects__entity___objectId_Parameters get_objects__entity___objectId_ParametersPathEntity get_objects__entity___objectId_ParametersPathObjectId = Get_objects__entity___objectId_Parameters{get_objects__entity___objectId_ParametersPathEntity = get_objects__entity___objectId_ParametersPathEntity,
                                                                                                                                                                                                  get_objects__entity___objectId_ParametersPathObjectId = get_objects__entity___objectId_ParametersPathObjectId}
-- | Represents a response of the operation 'get_objects__entity___objectId_'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Get_objects__entity___objectId_ResponseError' is used.
data Get_objects__entity___objectId_Response =
   Get_objects__entity___objectId_ResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Get_objects__entity___objectId_Response200 Get_objects__entity___objectId_ResponseBody200Variants -- ^ An entity object
  | Get_objects__entity___objectId_Response400 Error400 -- ^ The operation was not successful
  | Get_objects__entity___objectId_Response404 Error400 -- ^ Object not found
  deriving (Show.Show, GHC.Classes.Eq)
-- | Defines the oneOf schema located at @paths.\/objects\/{entity}\/{objectId}.GET.responses.200.content.application\/json.schema.oneOf@ in the specification.
-- 
-- 
data Get_objects__entity___objectId_ResponseBody200Variants =
   Get_objects__entity___objectId_ResponseBody200Product Product
  | Get_objects__entity___objectId_ResponseBody200Chore Chore
  | Get_objects__entity___objectId_ResponseBody200Battery Battery
  | Get_objects__entity___objectId_ResponseBody200Location Location
  | Get_objects__entity___objectId_ResponseBody200QuantityUnit QuantityUnit
  | Get_objects__entity___objectId_ResponseBody200ShoppingListItem ShoppingListItem
  | Get_objects__entity___objectId_ResponseBody200StockEntry StockEntry
  | Get_objects__entity___objectId_ResponseBody200ProductBarcode ProductBarcode
  deriving (Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_objects__entity___objectId_ResponseBody200Variants
    where {toJSON (Get_objects__entity___objectId_ResponseBody200Product a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200Chore a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200Battery a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200Location a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200QuantityUnit a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200ShoppingListItem a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200StockEntry a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Get_objects__entity___objectId_ResponseBody200ProductBarcode a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Get_objects__entity___objectId_ResponseBody200Variants
    where {parseJSON val = case (Get_objects__entity___objectId_ResponseBody200Product Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200Chore Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200Battery Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200Location Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200QuantityUnit Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200ShoppingListItem Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200StockEntry Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> ((Get_objects__entity___objectId_ResponseBody200ProductBarcode Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) Base.<|> Data.Aeson.Types.Internal.Error "No variant matched"))))))) of
                           {Data.Aeson.Types.Internal.Success a -> Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | > GET /objects/{entity}/{objectId}
-- 
-- The same as 'get_objects__entity___objectId_' but accepts an explicit configuration.
get_objects__entity___objectId_WithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_objects__entity___objectId_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Get_objects__entity___objectId_Response) -- ^ Monadic computation which returns the result of the operation
get_objects__entity___objectId_WithConfiguration config
                                                 parameters = Base.fmap (\response_4 -> Base.fmap (Data.Either.either Get_objects__entity___objectId_ResponseError Base.id Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Get_objects__entity___objectId_ResponseBody200Variants)
                                                                                                                                                                                                                                                                         | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Error400)
                                                                                                                                                                                                                                                                         | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Get_objects__entity___objectId_Response404 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Error400)
                                                                                                                                                                                                                                                                         | Base.otherwise -> Data.Either.Left "Missing default response type") response_4) response_4) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") ("/objects/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathEntity parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathObjectId parameters))) Base.<> "")))) Base.mempty)
-- | > GET /objects/{entity}/{objectId}
-- 
-- The same as 'get_objects__entity___objectId_' but returns the raw 'Data.ByteString.ByteString'.
get_objects__entity___objectId_Raw :: forall m . GrocyClient.Common.MonadHTTP m => Get_objects__entity___objectId_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_objects__entity___objectId_Raw parameters = Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") ("/objects/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathEntity parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathObjectId parameters))) Base.<> "")))) Base.mempty)
-- | > GET /objects/{entity}/{objectId}
-- 
-- The same as 'get_objects__entity___objectId_' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
get_objects__entity___objectId_WithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_objects__entity___objectId_Parameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_objects__entity___objectId_WithConfigurationRaw config
                                                    parameters = Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") ("/objects/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathEntity parameters))) Base.<> ("/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel (get_objects__entity___objectId_ParametersPathObjectId parameters))) Base.<> "")))) Base.mempty)
