-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation get_users
module GrocyClient.Operations.Get_users where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > GET /users
-- 
-- Returns all users
get_users :: forall m . GrocyClient.Common.MonadHTTP m => Get_usersParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Get_usersResponse) -- ^ Monadic computation which returns the result of the operation
get_users parameters = GHC.Internal.Base.fmap (\response_0 -> GHC.Internal.Base.fmap (GHC.Internal.Data.Either.either Get_usersResponseError GHC.Internal.Base.id GHC.Internal.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse200 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [UserDto])
                                                                                                                                                                                                            | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse400 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error400)
                                                                                                                                                                                                            | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 500) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse500 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error500)
                                                                                                                                                                                                            | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/users" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/users.GET.parameters@ in the specification.
-- 
-- 
data Get_usersParameters = Get_usersParameters {
  -- | queryLimit: Represents the parameter named \'limit\'
  -- 
  -- The maximum number of objects to return
  get_usersParametersQueryLimit :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  -- | queryOffset: Represents the parameter named \'offset\'
  -- 
  -- The number of objects to skip
  , get_usersParametersQueryOffset :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  -- | queryOrder: Represents the parameter named \'order\'
  -- 
  -- A valid field name by which the response should be ordered, use the separator \`:\` to specify the sort order (\`asc\` or \`desc\`, defaults to \`asc\` when omitted)
  , get_usersParametersQueryOrder :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | queryQuery[]: Represents the parameter named \'query[]\'
  -- 
  -- An array of filter conditions, each of them is a string in the form of \`\<field>\<condition>\<value>\` where\<br>\`\<field>\` is a valid field name\<br>\`\<condition>\` is a comparison operator, one of\<br>&nbsp;&nbsp;\`=\` equal\<br>&nbsp;&nbsp;\`!=\` not equal\<br>&nbsp;&nbsp;\`~\` LIKE\<br>&nbsp;&nbsp;\`!~\` not LIKE\<br>&nbsp;&nbsp;\`\<\` less\<br>&nbsp;&nbsp;\`>\` greater\<br>&nbsp;&nbsp;\`\<=\` less or equal\<br>&nbsp;&nbsp;\`>=\` greater or equal\<br>&nbsp;&nbsp;\`§\` regular expression\<br>\`\<value>\` is the value to search for
  , get_usersParametersQueryQuery__ :: (GHC.Internal.Maybe.Maybe [Data.Text.Internal.Text])
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_usersParameters
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryLimit" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryLimit obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryOffset" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryOffset obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryOrder" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryOrder obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryQuery[]" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryQuery__ obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryLimit" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryLimit obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryOffset" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryOffset obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryOrder" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryOrder obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("queryQuery[]" Data.Aeson.Types.ToJSON..=)) (get_usersParametersQueryQuery__ obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Get_usersParameters
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_usersParameters" (\obj -> (((GHC.Internal.Base.pure Get_usersParameters GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryLimit")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryOffset")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryOrder")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryQuery[]"))}
-- | Create a new 'Get_usersParameters' with all required fields.
mkGet_usersParameters :: Get_usersParameters
mkGet_usersParameters = Get_usersParameters{get_usersParametersQueryLimit = GHC.Internal.Maybe.Nothing,
                                            get_usersParametersQueryOffset = GHC.Internal.Maybe.Nothing,
                                            get_usersParametersQueryOrder = GHC.Internal.Maybe.Nothing,
                                            get_usersParametersQueryQuery__ = GHC.Internal.Maybe.Nothing}
-- | Represents a response of the operation 'get_users'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Get_usersResponseError' is used.
data Get_usersResponse =
   Get_usersResponseError GHC.Internal.Base.String -- ^ Means either no matching case available or a parse error
  | Get_usersResponse200 [UserDto] -- ^ A list of user objects
  | Get_usersResponse400 Error400 -- ^ The operation was not successful
  | Get_usersResponse500 Error500 -- ^ The operation was not successful (possible errors are invalid field names or conditions in filter parameters provided)
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
-- | > GET /users
-- 
-- The same as 'get_users' but accepts an explicit configuration.
get_usersWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_usersParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Get_usersResponse) -- ^ Monadic computation which returns the result of the operation
get_usersWithConfiguration config
                           parameters = GHC.Internal.Base.fmap (\response_4 -> GHC.Internal.Base.fmap (GHC.Internal.Data.Either.either Get_usersResponseError GHC.Internal.Base.id GHC.Internal.Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse200 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [UserDto])
                                                                                                                                                                                                                             | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse400 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Error400)
                                                                                                                                                                                                                             | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 500) (Network.HTTP.Client.Types.responseStatus response) -> Get_usersResponse500 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Error500)
                                                                                                                                                                                                                             | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type") response_4) response_4) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/users" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /users
-- 
-- The same as 'get_users' but returns the raw 'Data.ByteString.ByteString'.
get_usersRaw :: forall m . GrocyClient.Common.MonadHTTP m => Get_usersParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_usersRaw parameters = GHC.Internal.Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/users" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /users
-- 
-- The same as 'get_users' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
get_usersWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_usersParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_usersWithConfigurationRaw config
                              parameters = GHC.Internal.Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/users" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON GHC.Internal.Data.Functor.<$> get_usersParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
