-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation get_tasks
module GrocyClient.Operations.Get_tasks where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > GET /tasks
-- 
-- Returns all tasks which are not done yet
get_tasks :: forall m . GrocyClient.Common.MonadHTTP m => Get_tasksParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Get_tasksResponse) -- ^ Monadic computation which returns the result of the operation
get_tasks parameters = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Get_tasksResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_tasksResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [CurrentTaskResponse])
                                                                                                                                                                                                            | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 500) (Network.HTTP.Client.Types.responseStatus response) -> Get_tasksResponse500 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error500)
                                                                                                                                                                                                            | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/tasks" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/tasks.GET.parameters@ in the specification.
-- 
-- 
data Get_tasksParameters = Get_tasksParameters {
  -- | queryLimit: Represents the parameter named \'limit\'
  -- 
  -- The maximum number of objects to return
  get_tasksParametersQueryLimit :: (Maybe.Maybe GHC.Types.Int)
  -- | queryOffset: Represents the parameter named \'offset\'
  -- 
  -- The number of objects to skip
  , get_tasksParametersQueryOffset :: (Maybe.Maybe GHC.Types.Int)
  -- | queryOrder: Represents the parameter named \'order\'
  -- 
  -- A valid field name by which the response should be ordered, use the separator \`:\` to specify the sort order (\`asc\` or \`desc\`, defaults to \`asc\` when omitted)
  , get_tasksParametersQueryOrder :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | queryQuery[]: Represents the parameter named \'query[]\'
  -- 
  -- An array of filter conditions, each of them is a string in the form of \`\<field>\<condition>\<value>\` where\<br>\`\<field>\` is a valid field name\<br>\`\<condition>\` is a comparison operator, one of\<br>&nbsp;&nbsp;\`=\` equal\<br>&nbsp;&nbsp;\`!=\` not equal\<br>&nbsp;&nbsp;\`~\` LIKE\<br>&nbsp;&nbsp;\`!~\` not LIKE\<br>&nbsp;&nbsp;\`\<\` less\<br>&nbsp;&nbsp;\`>\` greater\<br>&nbsp;&nbsp;\`\<=\` less or equal\<br>&nbsp;&nbsp;\`>=\` greater or equal\<br>&nbsp;&nbsp;\`§\` regular expression\<br>\`\<value>\` is the value to search for
  , get_tasksParametersQueryQuery__ :: (Maybe.Maybe [Data.Text.Internal.Text])
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_tasksParameters
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryLimit" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryLimit obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryOffset" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryOffset obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryOrder" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryOrder obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryQuery[]" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryQuery__ obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryLimit" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryLimit obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryOffset" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryOffset obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryOrder" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryOrder obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("queryQuery[]" Data.Aeson.Types.ToJSON..=)) (get_tasksParametersQueryQuery__ obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Get_tasksParameters
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_tasksParameters" (\obj -> (((Base.pure Get_tasksParameters Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryLimit")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryOffset")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryOrder")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryQuery[]"))}
-- | Create a new 'Get_tasksParameters' with all required fields.
mkGet_tasksParameters :: Get_tasksParameters
mkGet_tasksParameters = Get_tasksParameters{get_tasksParametersQueryLimit = Maybe.Nothing,
                                            get_tasksParametersQueryOffset = Maybe.Nothing,
                                            get_tasksParametersQueryOrder = Maybe.Nothing,
                                            get_tasksParametersQueryQuery__ = Maybe.Nothing}
-- | Represents a response of the operation 'get_tasks'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Get_tasksResponseError' is used.
data Get_tasksResponse =
   Get_tasksResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Get_tasksResponse200 [CurrentTaskResponse] -- ^ An array of CurrentTaskResponse objects
  | Get_tasksResponse500 Error500 -- ^ The operation was not successful (possible errors are invalid field names or conditions in filter parameters provided)
  deriving (Show.Show, GHC.Classes.Eq)
-- | > GET /tasks
-- 
-- The same as 'get_tasks' but accepts an explicit configuration.
get_tasksWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_tasksParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Get_tasksResponse) -- ^ Monadic computation which returns the result of the operation
get_tasksWithConfiguration config
                           parameters = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Get_tasksResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_tasksResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [CurrentTaskResponse])
                                                                                                                                                                                                                             | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 500) (Network.HTTP.Client.Types.responseStatus response) -> Get_tasksResponse500 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Error500)
                                                                                                                                                                                                                             | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/tasks" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /tasks
-- 
-- The same as 'get_tasks' but returns the raw 'Data.ByteString.ByteString'.
get_tasksRaw :: forall m . GrocyClient.Common.MonadHTTP m => Get_tasksParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_tasksRaw parameters = Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/tasks" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                        GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /tasks
-- 
-- The same as 'get_tasks' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
get_tasksWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Get_tasksParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_tasksWithConfigurationRaw config
                              parameters = Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/tasks" [GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "query[]") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryQuery__ parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "order") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOrder parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "limit") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryLimit parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                               GrocyClient.Common.QueryParameter (Data.Text.Internal.pack "offset") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_tasksParametersQueryOffset parameters) (Data.Text.Internal.pack "form") GHC.Types.False])
