-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation get_system_info
module GrocyClient.Operations.Get_system_info where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > GET /system/info
-- 
-- Returns information about the installed Grocy version, PHP runtime and OS
get_system_info :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Get_system_infoResponse) -- ^ Monadic computation which returns the result of the operation
get_system_info = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Get_system_infoResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_system_infoResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Get_system_infoResponseBody200)
                                                                                                                                                                                                             | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/system/info" Base.mempty)
-- | Represents a response of the operation 'get_system_info'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Get_system_infoResponseError' is used.
data Get_system_infoResponse =
   Get_system_infoResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Get_system_infoResponse200 Get_system_infoResponseBody200 -- ^ An DbChangedTimeResponse object
  deriving (Show.Show, GHC.Classes.Eq)
-- | Defines the object schema located at @paths.\/system\/info.GET.responses.200.content.application\/json.schema@ in the specification.
-- 
-- 
data Get_system_infoResponseBody200 = Get_system_infoResponseBody200 {
  -- | grocy_version
  get_system_infoResponseBody200Grocy_version :: (Maybe.Maybe Get_system_infoResponseBody200Grocy_version)
  -- | php_version
  , get_system_infoResponseBody200Php_version :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | sqlite_version
  , get_system_infoResponseBody200Sqlite_version :: (Maybe.Maybe Data.Text.Internal.Text)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_system_infoResponseBody200
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("grocy_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_version obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("php_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Php_version obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("sqlite_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Sqlite_version obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("grocy_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_version obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("php_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Php_version obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("sqlite_version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Sqlite_version obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Get_system_infoResponseBody200
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_system_infoResponseBody200" (\obj -> ((Base.pure Get_system_infoResponseBody200 Base.<*> (obj Data.Aeson.Types.FromJSON..:! "grocy_version")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "php_version")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "sqlite_version"))}
-- | Create a new 'Get_system_infoResponseBody200' with all required fields.
mkGet_system_infoResponseBody200 :: Get_system_infoResponseBody200
mkGet_system_infoResponseBody200 = Get_system_infoResponseBody200{get_system_infoResponseBody200Grocy_version = Maybe.Nothing,
                                                                  get_system_infoResponseBody200Php_version = Maybe.Nothing,
                                                                  get_system_infoResponseBody200Sqlite_version = Maybe.Nothing}
-- | Defines the object schema located at @paths.\/system\/info.GET.responses.200.content.application\/json.schema.properties.grocy_version@ in the specification.
-- 
-- 
data Get_system_infoResponseBody200Grocy_version = Get_system_infoResponseBody200Grocy_version {
  -- | ReleaseDate
  get_system_infoResponseBody200Grocy_versionReleaseDate :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | Version
  , get_system_infoResponseBody200Grocy_versionVersion :: (Maybe.Maybe Data.Text.Internal.Text)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_system_infoResponseBody200Grocy_version
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("ReleaseDate" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_versionReleaseDate obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("Version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_versionVersion obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("ReleaseDate" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_versionReleaseDate obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("Version" Data.Aeson.Types.ToJSON..=)) (get_system_infoResponseBody200Grocy_versionVersion obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Get_system_infoResponseBody200Grocy_version
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_system_infoResponseBody200Grocy_version" (\obj -> (Base.pure Get_system_infoResponseBody200Grocy_version Base.<*> (obj Data.Aeson.Types.FromJSON..:! "ReleaseDate")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "Version"))}
-- | Create a new 'Get_system_infoResponseBody200Grocy_version' with all required fields.
mkGet_system_infoResponseBody200Grocy_version :: Get_system_infoResponseBody200Grocy_version
mkGet_system_infoResponseBody200Grocy_version = Get_system_infoResponseBody200Grocy_version{get_system_infoResponseBody200Grocy_versionReleaseDate = Maybe.Nothing,
                                                                                            get_system_infoResponseBody200Grocy_versionVersion = Maybe.Nothing}
-- | > GET /system/info
-- 
-- The same as 'get_system_info' but accepts an explicit configuration.
get_system_infoWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> m (Network.HTTP.Client.Types.Response Get_system_infoResponse) -- ^ Monadic computation which returns the result of the operation
get_system_infoWithConfiguration config = Base.fmap (\response_2 -> Base.fmap (Data.Either.either Get_system_infoResponseError Base.id Base.. (\response body -> if | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_system_infoResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Get_system_infoResponseBody200)
                                                                                                                                                                                                                                     | Base.otherwise -> Data.Either.Left "Missing default response type") response_2) response_2) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/system/info" Base.mempty)
-- | > GET /system/info
-- 
-- The same as 'get_system_info' but returns the raw 'Data.ByteString.ByteString'.
get_system_infoRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_system_infoRaw = Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/system/info" Base.mempty)
-- | > GET /system/info
-- 
-- The same as 'get_system_info' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
get_system_infoWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
get_system_infoWithConfigurationRaw config = Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "GET") "/system/info" Base.mempty)
