-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation post_chores_executions_calculate_next_assignments
module GrocyClient.Operations.Post_chores_executions_calculate_next_assignments where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > POST /chores/executions/calculate-next-assignments
-- 
-- (Re)calculates all next user assignments of all chores
post_chores_executions_calculate_next_assignments :: forall m . GrocyClient.Common.MonadHTTP m => Maybe.Maybe Post_chores_executions_calculate_next_assignmentsRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Post_chores_executions_calculate_next_assignmentsResponse) -- ^ Monadic computation which returns the result of the operation
post_chores_executions_calculate_next_assignments body = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Post_chores_executions_calculate_next_assignmentsResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Post_chores_executions_calculate_next_assignmentsResponse204
                                                                                                                                                                                                                                                                                      | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores_executions_calculate_next_assignmentsResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Error400)
                                                                                                                                                                                                                                                                                      | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/chores/executions/calculate-next-assignments" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/chores\/executions\/calculate-next-assignments.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data Post_chores_executions_calculate_next_assignmentsRequestBody = Post_chores_executions_calculate_next_assignmentsRequestBody {
  -- | chore_id: The chore id of the chore which next user assignment should be (re)calculated, when omitted, the next user assignments of all chores will (re)caluclated
  post_chores_executions_calculate_next_assignmentsRequestBodyChore_id :: (Maybe.Maybe GHC.Types.Int)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Post_chores_executions_calculate_next_assignmentsRequestBody
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("chore_id" Data.Aeson.Types.ToJSON..=)) (post_chores_executions_calculate_next_assignmentsRequestBodyChore_id obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("chore_id" Data.Aeson.Types.ToJSON..=)) (post_chores_executions_calculate_next_assignmentsRequestBodyChore_id obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Post_chores_executions_calculate_next_assignmentsRequestBody
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Post_chores_executions_calculate_next_assignmentsRequestBody" (\obj -> Base.pure Post_chores_executions_calculate_next_assignmentsRequestBody Base.<*> (obj Data.Aeson.Types.FromJSON..:! "chore_id"))}
-- | Create a new 'Post_chores_executions_calculate_next_assignmentsRequestBody' with all required fields.
mkPost_chores_executions_calculate_next_assignmentsRequestBody :: Post_chores_executions_calculate_next_assignmentsRequestBody
mkPost_chores_executions_calculate_next_assignmentsRequestBody = Post_chores_executions_calculate_next_assignmentsRequestBody{post_chores_executions_calculate_next_assignmentsRequestBodyChore_id = Maybe.Nothing}
-- | Represents a response of the operation 'post_chores_executions_calculate_next_assignments'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Post_chores_executions_calculate_next_assignmentsResponseError' is used.
data Post_chores_executions_calculate_next_assignmentsResponse =
   Post_chores_executions_calculate_next_assignmentsResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Post_chores_executions_calculate_next_assignmentsResponse204 -- ^ The operation was successful
  | Post_chores_executions_calculate_next_assignmentsResponse400 Error400 -- ^ The operation was not successful
  deriving (Show.Show, GHC.Classes.Eq)
-- | > POST /chores/executions/calculate-next-assignments
-- 
-- The same as 'post_chores_executions_calculate_next_assignments' but accepts an explicit configuration.
post_chores_executions_calculate_next_assignmentsWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Maybe.Maybe Post_chores_executions_calculate_next_assignmentsRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Post_chores_executions_calculate_next_assignmentsResponse) -- ^ Monadic computation which returns the result of the operation
post_chores_executions_calculate_next_assignmentsWithConfiguration config
                                                                   body = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Post_chores_executions_calculate_next_assignmentsResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Post_chores_executions_calculate_next_assignmentsResponse204
                                                                                                                                                                                                                                                                                                       | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores_executions_calculate_next_assignmentsResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Error400)
                                                                                                                                                                                                                                                                                                       | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/chores/executions/calculate-next-assignments" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /chores/executions/calculate-next-assignments
-- 
-- The same as 'post_chores_executions_calculate_next_assignments' but returns the raw 'Data.ByteString.ByteString'.
post_chores_executions_calculate_next_assignmentsRaw :: forall m . GrocyClient.Common.MonadHTTP m => Maybe.Maybe Post_chores_executions_calculate_next_assignmentsRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_chores_executions_calculate_next_assignmentsRaw body = Base.id (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/chores/executions/calculate-next-assignments" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /chores/executions/calculate-next-assignments
-- 
-- The same as 'post_chores_executions_calculate_next_assignments' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
post_chores_executions_calculate_next_assignmentsWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Maybe.Maybe Post_chores_executions_calculate_next_assignmentsRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_chores_executions_calculate_next_assignmentsWithConfigurationRaw config
                                                                      body = Base.id (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/chores/executions/calculate-next-assignments" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
