-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation post_batteries__batteryId__charge
module GrocyClient.Operations.Post_batteries__batteryId__charge where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > POST /batteries/{batteryId}/charge
-- 
-- Tracks a charge cycle of the given battery
post_batteries__batteryId__charge :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ batteryId: A valid battery id
  -> Post_batteries__batteryId__chargeRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Post_batteries__batteryId__chargeResponse) -- ^ Monadic computation which returns the result of the operation
post_batteries__batteryId__charge batteryId
                                  body = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Post_batteries__batteryId__chargeResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries__batteryId__chargeResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          BatteryChargeCycleEntry)
                                                                                                                                                                                                                                                      | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries__batteryId__chargeResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Error400)
                                                                                                                                                                                                                                                      | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/batteries/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel batteryId)) Base.<> "/charge")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/batteries\/{batteryId}\/charge.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data Post_batteries__batteryId__chargeRequestBody = Post_batteries__batteryId__chargeRequestBody {
  -- | tracked_time: The time of when the battery was charged, when omitted, the current time is used
  post_batteries__batteryId__chargeRequestBodyTracked_time :: (Maybe.Maybe Data.Text.Internal.Text)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Post_batteries__batteryId__chargeRequestBody
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("tracked_time" Data.Aeson.Types.ToJSON..=)) (post_batteries__batteryId__chargeRequestBodyTracked_time obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("tracked_time" Data.Aeson.Types.ToJSON..=)) (post_batteries__batteryId__chargeRequestBodyTracked_time obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Post_batteries__batteryId__chargeRequestBody
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Post_batteries__batteryId__chargeRequestBody" (\obj -> Base.pure Post_batteries__batteryId__chargeRequestBody Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tracked_time"))}
-- | Create a new 'Post_batteries__batteryId__chargeRequestBody' with all required fields.
mkPost_batteries__batteryId__chargeRequestBody :: Post_batteries__batteryId__chargeRequestBody
mkPost_batteries__batteryId__chargeRequestBody = Post_batteries__batteryId__chargeRequestBody{post_batteries__batteryId__chargeRequestBodyTracked_time = Maybe.Nothing}
-- | Represents a response of the operation 'post_batteries__batteryId__charge'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Post_batteries__batteryId__chargeResponseError' is used.
data Post_batteries__batteryId__chargeResponse =
   Post_batteries__batteryId__chargeResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Post_batteries__batteryId__chargeResponse200 BatteryChargeCycleEntry -- ^ The operation was successful
  | Post_batteries__batteryId__chargeResponse400 Error400 -- ^ The operation was not successful (possible errors are: Not existing battery)
  deriving (Show.Show, GHC.Classes.Eq)
-- | > POST /batteries/{batteryId}/charge
-- 
-- The same as 'post_batteries__batteryId__charge' but accepts an explicit configuration.
post_batteries__batteryId__chargeWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ batteryId: A valid battery id
  -> Post_batteries__batteryId__chargeRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Post_batteries__batteryId__chargeResponse) -- ^ Monadic computation which returns the result of the operation
post_batteries__batteryId__chargeWithConfiguration config
                                                   batteryId
                                                   body = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Post_batteries__batteryId__chargeResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries__batteryId__chargeResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           BatteryChargeCycleEntry)
                                                                                                                                                                                                                                                                       | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries__batteryId__chargeResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Error400)
                                                                                                                                                                                                                                                                       | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/batteries/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel batteryId)) Base.<> "/charge")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /batteries/{batteryId}/charge
-- 
-- The same as 'post_batteries__batteryId__charge' but returns the raw 'Data.ByteString.ByteString'.
post_batteries__batteryId__chargeRaw :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ batteryId: A valid battery id
  -> Post_batteries__batteryId__chargeRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_batteries__batteryId__chargeRaw batteryId
                                     body = Base.id (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/batteries/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel batteryId)) Base.<> "/charge")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /batteries/{batteryId}/charge
-- 
-- The same as 'post_batteries__batteryId__charge' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
post_batteries__batteryId__chargeWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ batteryId: A valid battery id
  -> Post_batteries__batteryId__chargeRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_batteries__batteryId__chargeWithConfigurationRaw config
                                                      batteryId
                                                      body = Base.id (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/batteries/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel batteryId)) Base.<> "/charge")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
