-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation post_chores__choreId__execute
module GrocyClient.Operations.Post_chores__choreId__execute where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > POST /chores/{choreId}/execute
-- 
-- Tracks an execution of the given chore
post_chores__choreId__execute :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ choreId: A valid chore id
  -> Post_chores__choreId__executeRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Post_chores__choreId__executeResponse) -- ^ Monadic computation which returns the result of the operation
post_chores__choreId__execute choreId
                              body = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Post_chores__choreId__executeResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores__choreId__executeResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ChoreLogEntry)
                                                                                                                                                                                                                                              | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores__choreId__executeResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Error400)
                                                                                                                                                                                                                                              | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/chores/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel choreId)) Base.<> "/execute")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/chores\/{choreId}\/execute.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data Post_chores__choreId__executeRequestBody = Post_chores__choreId__executeRequestBody {
  -- | done_by: A valid user id of who executed this chore, when omitted, the currently authenticated user will be used
  post_chores__choreId__executeRequestBodyDone_by :: (Maybe.Maybe GHC.Types.Int)
  -- | skipped: \`true\` when the execution should be tracked as skipped, defaults to \`false\` when omitted
  , post_chores__choreId__executeRequestBodySkipped :: (Maybe.Maybe GHC.Types.Bool)
  -- | tracked_time: The time of when the chore was executed, when omitted, the current time is used
  , post_chores__choreId__executeRequestBodyTracked_time :: (Maybe.Maybe Data.Text.Internal.Text)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Post_chores__choreId__executeRequestBody
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("done_by" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodyDone_by obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("skipped" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodySkipped obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("tracked_time" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodyTracked_time obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("done_by" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodyDone_by obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("skipped" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodySkipped obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("tracked_time" Data.Aeson.Types.ToJSON..=)) (post_chores__choreId__executeRequestBodyTracked_time obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Post_chores__choreId__executeRequestBody
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Post_chores__choreId__executeRequestBody" (\obj -> ((Base.pure Post_chores__choreId__executeRequestBody Base.<*> (obj Data.Aeson.Types.FromJSON..:! "done_by")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "skipped")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tracked_time"))}
-- | Create a new 'Post_chores__choreId__executeRequestBody' with all required fields.
mkPost_chores__choreId__executeRequestBody :: Post_chores__choreId__executeRequestBody
mkPost_chores__choreId__executeRequestBody = Post_chores__choreId__executeRequestBody{post_chores__choreId__executeRequestBodyDone_by = Maybe.Nothing,
                                                                                      post_chores__choreId__executeRequestBodySkipped = Maybe.Nothing,
                                                                                      post_chores__choreId__executeRequestBodyTracked_time = Maybe.Nothing}
-- | Represents a response of the operation 'post_chores__choreId__execute'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Post_chores__choreId__executeResponseError' is used.
data Post_chores__choreId__executeResponse =
   Post_chores__choreId__executeResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Post_chores__choreId__executeResponse200 ChoreLogEntry -- ^ The operation was successful
  | Post_chores__choreId__executeResponse400 Error400 -- ^ The operation was not successful (possible errors are: Not existing chore)
  deriving (Show.Show, GHC.Classes.Eq)
-- | > POST /chores/{choreId}/execute
-- 
-- The same as 'post_chores__choreId__execute' but accepts an explicit configuration.
post_chores__choreId__executeWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ choreId: A valid chore id
  -> Post_chores__choreId__executeRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Post_chores__choreId__executeResponse) -- ^ Monadic computation which returns the result of the operation
post_chores__choreId__executeWithConfiguration config
                                               choreId
                                               body = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Post_chores__choreId__executeResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores__choreId__executeResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ChoreLogEntry)
                                                                                                                                                                                                                                                               | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_chores__choreId__executeResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Error400)
                                                                                                                                                                                                                                                               | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/chores/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel choreId)) Base.<> "/execute")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /chores/{choreId}/execute
-- 
-- The same as 'post_chores__choreId__execute' but returns the raw 'Data.ByteString.ByteString'.
post_chores__choreId__executeRaw :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ choreId: A valid chore id
  -> Post_chores__choreId__executeRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_chores__choreId__executeRaw choreId
                                 body = Base.id (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/chores/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel choreId)) Base.<> "/execute")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /chores/{choreId}/execute
-- 
-- The same as 'post_chores__choreId__execute' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
post_chores__choreId__executeWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ choreId: A valid chore id
  -> Post_chores__choreId__executeRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_chores__choreId__executeWithConfigurationRaw config
                                                  choreId
                                                  body = Base.id (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") ("/chores/" Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True Base.$ (GrocyClient.Common.textToByte Base.$ GrocyClient.Common.stringifyModel choreId)) Base.<> "/execute")) Base.mempty (Maybe.Just body) GrocyClient.Common.RequestBodyEncodingJSON)
