-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation post_batteries_charge_cycles__chargeCycleId__undo
module GrocyClient.Operations.Post_batteries_charge_cycles__chargeCycleId__undo where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > POST /batteries/charge-cycles/{chargeCycleId}/undo
-- 
-- Undoes a battery charge cycle
post_batteries_charge_cycles__chargeCycleId__undo :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ chargeCycleId: A valid charge cycle id
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Post_batteries_charge_cycles__chargeCycleId__undoResponse) -- ^ Monadic computation which returns the result of the operation
post_batteries_charge_cycles__chargeCycleId__undo chargeCycleId = GHC.Internal.Base.fmap (\response_0 -> GHC.Internal.Base.fmap (GHC.Internal.Data.Either.either Post_batteries_charge_cycles__chargeCycleId__undoResponseError GHC.Internal.Base.id GHC.Internal.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> GHC.Internal.Data.Either.Right Post_batteries_charge_cycles__chargeCycleId__undoResponse204
                                                                                                                                                                                                                                                                                               | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries_charge_cycles__chargeCycleId__undoResponse400 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Error400)
                                                                                                                                                                                                                                                                                               | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") ("/batteries/charge-cycles/" GHC.Internal.Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Internal.Base.$ (GrocyClient.Common.textToByte GHC.Internal.Base.$ GrocyClient.Common.stringifyModel chargeCycleId)) GHC.Internal.Base.<> "/undo")) GHC.Internal.Base.mempty)
-- | Represents a response of the operation 'post_batteries_charge_cycles__chargeCycleId__undo'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Post_batteries_charge_cycles__chargeCycleId__undoResponseError' is used.
data Post_batteries_charge_cycles__chargeCycleId__undoResponse =
   Post_batteries_charge_cycles__chargeCycleId__undoResponseError GHC.Internal.Base.String -- ^ Means either no matching case available or a parse error
  | Post_batteries_charge_cycles__chargeCycleId__undoResponse204 -- ^ The operation was successful
  | Post_batteries_charge_cycles__chargeCycleId__undoResponse400 Error400 -- ^ The operation was not successful (possible errors are: Not existing booking)
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
-- | > POST /batteries/charge-cycles/{chargeCycleId}/undo
-- 
-- The same as 'post_batteries_charge_cycles__chargeCycleId__undo' but accepts an explicit configuration.
post_batteries_charge_cycles__chargeCycleId__undoWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ chargeCycleId: A valid charge cycle id
  -> m (Network.HTTP.Client.Types.Response Post_batteries_charge_cycles__chargeCycleId__undoResponse) -- ^ Monadic computation which returns the result of the operation
post_batteries_charge_cycles__chargeCycleId__undoWithConfiguration config
                                                                   chargeCycleId = GHC.Internal.Base.fmap (\response_3 -> GHC.Internal.Base.fmap (GHC.Internal.Data.Either.either Post_batteries_charge_cycles__chargeCycleId__undoResponseError GHC.Internal.Base.id GHC.Internal.Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> GHC.Internal.Data.Either.Right Post_batteries_charge_cycles__chargeCycleId__undoResponse204
                                                                                                                                                                                                                                                                                                                | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_batteries_charge_cycles__chargeCycleId__undoResponse400 GHC.Internal.Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: GHC.Internal.Data.Either.Either GHC.Internal.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Error400)
                                                                                                                                                                                                                                                                                                                | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") ("/batteries/charge-cycles/" GHC.Internal.Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Internal.Base.$ (GrocyClient.Common.textToByte GHC.Internal.Base.$ GrocyClient.Common.stringifyModel chargeCycleId)) GHC.Internal.Base.<> "/undo")) GHC.Internal.Base.mempty)
-- | > POST /batteries/charge-cycles/{chargeCycleId}/undo
-- 
-- The same as 'post_batteries_charge_cycles__chargeCycleId__undo' but returns the raw 'Data.ByteString.ByteString'.
post_batteries_charge_cycles__chargeCycleId__undoRaw :: forall m . GrocyClient.Common.MonadHTTP m => GHC.Types.Int -- ^ chargeCycleId: A valid charge cycle id
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_batteries_charge_cycles__chargeCycleId__undoRaw chargeCycleId = GHC.Internal.Base.id (GrocyClient.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") ("/batteries/charge-cycles/" GHC.Internal.Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Internal.Base.$ (GrocyClient.Common.textToByte GHC.Internal.Base.$ GrocyClient.Common.stringifyModel chargeCycleId)) GHC.Internal.Base.<> "/undo")) GHC.Internal.Base.mempty)
-- | > POST /batteries/charge-cycles/{chargeCycleId}/undo
-- 
-- The same as 'post_batteries_charge_cycles__chargeCycleId__undo' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
post_batteries_charge_cycles__chargeCycleId__undoWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ chargeCycleId: A valid charge cycle id
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_batteries_charge_cycles__chargeCycleId__undoWithConfigurationRaw config
                                                                      chargeCycleId = GHC.Internal.Base.id (GrocyClient.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") ("/batteries/charge-cycles/" GHC.Internal.Base.<> (GrocyClient.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Internal.Base.$ (GrocyClient.Common.textToByte GHC.Internal.Base.$ GrocyClient.Common.stringifyModel chargeCycleId)) GHC.Internal.Base.<> "/undo")) GHC.Internal.Base.mempty)
