-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation post_stock_shoppinglist_clear
module GrocyClient.Operations.Post_stock_shoppinglist_clear where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified GrocyClient.Common
import GrocyClient.Types

-- | > POST /stock/shoppinglist/clear
-- 
-- Removes all items from the given shopping list
post_stock_shoppinglist_clear :: forall m . GrocyClient.Common.MonadHTTP m => Maybe.Maybe Post_stock_shoppinglist_clearRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Post_stock_shoppinglist_clearResponse) -- ^ Monadic computation which returns the result of the operation
post_stock_shoppinglist_clear body = Base.fmap (\response_0 -> Base.fmap (Data.Either.either Post_stock_shoppinglist_clearResponseError Base.id Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Post_stock_shoppinglist_clearResponse204
                                                                                                                                                                                                                                              | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_stock_shoppinglist_clearResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Error400)
                                                                                                                                                                                                                                              | Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/stock/shoppinglist/clear" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/stock\/shoppinglist\/clear.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data Post_stock_shoppinglist_clearRequestBody = Post_stock_shoppinglist_clearRequestBody {
  -- | done_only: When \`true\`, only done items will be removed (defaults to \`false\` when ommited)
  post_stock_shoppinglist_clearRequestBodyDone_only :: (Maybe.Maybe GHC.Types.Bool)
  -- | list_id: The shopping list id to clear, when omitted, the default shopping list (with id 1) is used
  , post_stock_shoppinglist_clearRequestBodyList_id :: (Maybe.Maybe GHC.Types.Int)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Post_stock_shoppinglist_clearRequestBody
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("done_only" Data.Aeson.Types.ToJSON..=)) (post_stock_shoppinglist_clearRequestBodyDone_only obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("list_id" Data.Aeson.Types.ToJSON..=)) (post_stock_shoppinglist_clearRequestBodyList_id obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("done_only" Data.Aeson.Types.ToJSON..=)) (post_stock_shoppinglist_clearRequestBodyDone_only obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("list_id" Data.Aeson.Types.ToJSON..=)) (post_stock_shoppinglist_clearRequestBodyList_id obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Post_stock_shoppinglist_clearRequestBody
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Post_stock_shoppinglist_clearRequestBody" (\obj -> (Base.pure Post_stock_shoppinglist_clearRequestBody Base.<*> (obj Data.Aeson.Types.FromJSON..:! "done_only")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "list_id"))}
-- | Create a new 'Post_stock_shoppinglist_clearRequestBody' with all required fields.
mkPost_stock_shoppinglist_clearRequestBody :: Post_stock_shoppinglist_clearRequestBody
mkPost_stock_shoppinglist_clearRequestBody = Post_stock_shoppinglist_clearRequestBody{post_stock_shoppinglist_clearRequestBodyDone_only = Maybe.Nothing,
                                                                                      post_stock_shoppinglist_clearRequestBodyList_id = Maybe.Nothing}
-- | Represents a response of the operation 'post_stock_shoppinglist_clear'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Post_stock_shoppinglist_clearResponseError' is used.
data Post_stock_shoppinglist_clearResponse =
   Post_stock_shoppinglist_clearResponseError Base.String -- ^ Means either no matching case available or a parse error
  | Post_stock_shoppinglist_clearResponse204 -- ^ The operation was successful
  | Post_stock_shoppinglist_clearResponse400 Error400 -- ^ The operation was not successful (possible errors are: Not existing shopping list)
  deriving (Show.Show, GHC.Classes.Eq)
-- | > POST /stock/shoppinglist/clear
-- 
-- The same as 'post_stock_shoppinglist_clear' but accepts an explicit configuration.
post_stock_shoppinglist_clearWithConfiguration :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Maybe.Maybe Post_stock_shoppinglist_clearRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Post_stock_shoppinglist_clearResponse) -- ^ Monadic computation which returns the result of the operation
post_stock_shoppinglist_clearWithConfiguration config
                                               body = Base.fmap (\response_3 -> Base.fmap (Data.Either.either Post_stock_shoppinglist_clearResponseError Base.id Base.. (\response body -> if | (\status_4 -> Network.HTTP.Types.Status.statusCode status_4 GHC.Classes.== 204) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Post_stock_shoppinglist_clearResponse204
                                                                                                                                                                                                                                                               | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Post_stock_shoppinglist_clearResponse400 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Error400)
                                                                                                                                                                                                                                                               | Base.otherwise -> Data.Either.Left "Missing default response type") response_3) response_3) (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/stock/shoppinglist/clear" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /stock/shoppinglist/clear
-- 
-- The same as 'post_stock_shoppinglist_clear' but returns the raw 'Data.ByteString.ByteString'.
post_stock_shoppinglist_clearRaw :: forall m . GrocyClient.Common.MonadHTTP m => Maybe.Maybe Post_stock_shoppinglist_clearRequestBody -- ^ The request body to send
  -> GrocyClient.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_stock_shoppinglist_clearRaw body = Base.id (GrocyClient.Common.doBodyCallWithConfigurationM (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/stock/shoppinglist/clear" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
-- | > POST /stock/shoppinglist/clear
-- 
-- The same as 'post_stock_shoppinglist_clear' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
post_stock_shoppinglist_clearWithConfigurationRaw :: forall m . GrocyClient.Common.MonadHTTP m => GrocyClient.Common.Configuration -- ^ The configuration to use in the request
  -> Maybe.Maybe Post_stock_shoppinglist_clearRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
post_stock_shoppinglist_clearWithConfigurationRaw config
                                                  body = Base.id (GrocyClient.Common.doBodyCallWithConfiguration config (Data.Text.toUpper Base.$ Data.Text.Internal.pack "POST") "/stock/shoppinglist/clear" Base.mempty body GrocyClient.Common.RequestBodyEncodingJSON)
