# NOTE: this file was generated by the Mobile NixOS installer.
{ config, lib, pkgs, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/7f9a6114-ea86-4bef-8487-aec03e1d38fa";
      fsType = "ext4";
    };
  };
  
  boot.initrd.luks.devices = {
    "LUKS-PINEPHONE-ROOTFS" = {
      device = "/dev/disk/by-uuid/fe4e606c-fe23-4e99-bc7a-6a22e3510de8";
    };
  };

  nix.settings.max-jobs = lib.mkDefault 2;
}
