{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Data.Text qualified as T
import Data.Text.IO qualified as TIO
import Network.HTTP.Client (newManager)
import Network.HTTP.Client.TLS (tlsManagerSettings)

import WalmartExtractor (Endpoints (..), discoverEndpoints)

main :: IO ()
main = do
  mgr <- newManager tlsManagerSettings
  eps <- discoverEndpoints mgr
  TIO.putStr (generateModule eps)

generateModule :: Endpoints -> T.Text
generateModule eps = T.unlines
  [ "-- GENERATED by walmart-extractor. Do not edit manually."
  , "{-# LANGUAGE OverloadedStrings #-}"
  , ""
  , "module Walmart.Internal.Endpoints where"
  , ""
  , "import Data.Text (Text)"
  , ""
  , "purchaseHistoryUrl :: Text"
  , "purchaseHistoryUrl = " <> showText (epPurchaseHistory eps)
  , ""
  , "getOrderUrl :: Text"
  , "getOrderUrl = " <> showText (epGetOrder eps)
  ]

showText :: T.Text -> T.Text
showText t = "\"" <> T.replace "\"" "\\\"" t <> "\""
