{ pkgs, ... }:
let
  background = "#282a36";
  background-alt = "#282a36";
  background-attention = "#181920";
  border = "#282a36";
  current-line = "#44475a";
  selection = "#44475a";
  foreground = "#f8f8f2";
  foreground-alt = "#e0e0e0";
  foreground-attention = "#ffffff";
  comment = "#6272a4";
  cyan = "#8be9fd";
  green = "#50fa7b";
  orange = "#ffb86c";
  pink = "#ff79c6";
  purple = "#bd93f9";
  red = "#ff5555";
  yellow = "#f1fa8c";
  spacing = {
    vertical = 5;
    horizontal = 5;
  };
  padding = {
    top = 6;
    right = 8;
    bottom = 6;
    left = 8;
  };
in {

  programs.qutebrowser = {
    package = pkgs.pinned.qutebrowser;
    enable = true;
    searchEngines = {
      DEFAULT = "https://search.trexd.dev/?search={}";
      np = "https://search.nixos.org/?search={}";
    };
    settings = {
      url.start_pages = "https://search.trexd.dev";
      url.default_page = "https://search.trexd.dev";
      colors.completion.category.bg = background;
      colors.completion.category.border.bottom = border;
      colors.completion.category.border.top = border;
      colors.completion.category.fg = foreground;
      colors.completion.even.bg = background;
      colors.completion.odd.bg = background-alt;
      colors.completion.fg = foreground;
      colors.completion.item.selected.bg = selection;
      colors.completion.item.selected.border.bottom = selection;
      colors.completion.item.selected.border.top = selection;
      colors.completion.item.selected.fg = foreground;
      colors.completion.match.fg = orange;
      colors.completion.scrollbar.bg = background;
      colors.completion.scrollbar.fg = foreground;
      colors.downloads.bar.bg = background;
      colors.downloads.error.bg = background;
      colors.downloads.error.fg = red;
      colors.downloads.stop.bg = background;
      colors.downloads.system.bg = "none";
      colors.hints.bg = background;
      colors.hints.fg = purple;
      hints.border = "1px solid ${background-alt}";
      colors.hints.match.fg = foreground-alt;
      colors.keyhint.bg = background;
      colors.keyhint.fg = purple;
      colors.keyhint.suffix.fg = selection;
      colors.messages.error.bg = background;
      colors.messages.error.border = background-alt;
      colors.messages.error.fg = red;
      colors.messages.info.bg = background;
      colors.messages.info.border = background-alt;
      colors.messages.info.fg = comment;
      colors.messages.warning.bg = background;
      colors.messages.warning.border = background-alt;
      colors.messages.warning.fg = red;
      colors.prompts.bg = background;
      colors.prompts.border = "1px solid ${background-alt}";
      colors.prompts.fg = cyan;
      colors.prompts.selected.bg = selection;
      colors.statusbar.caret.bg = background;
      colors.statusbar.caret.fg = orange;
      colors.statusbar.caret.selection.bg = background;
      colors.statusbar.caret.selection.fg = orange;
      colors.statusbar.command.bg = background;
      colors.statusbar.command.fg = pink;
      colors.statusbar.command.private.bg = background;
      colors.statusbar.command.private.fg = foreground-alt;
      colors.statusbar.insert.bg = background-attention;
      colors.statusbar.insert.fg = foreground-attention;
      colors.statusbar.normal.bg = background;
      colors.statusbar.normal.fg = foreground;
      colors.statusbar.passthrough.bg = background;
      colors.statusbar.passthrough.fg = orange;
      colors.statusbar.private.bg = background-alt;
      colors.statusbar.private.fg = foreground-alt;
      colors.statusbar.progress.bg = background;
      colors.statusbar.url.error.fg = red;
      colors.statusbar.url.fg = foreground;
      colors.statusbar.url.hover.fg = cyan;
      colors.statusbar.url.success.http.fg = green;
      colors.statusbar.url.success.https.fg = green;
      colors.statusbar.url.warn.fg = yellow;
      colors.tabs.bar.bg = selection;
      colors.tabs.even.bg = selection;
      colors.tabs.even.fg = foreground;
      colors.tabs.indicator.error = red;
      colors.tabs.indicator.start = orange;
      colors.tabs.indicator.stop = green;
      colors.tabs.indicator.system = "none";
      colors.tabs.odd.bg = selection;
      colors.tabs.odd.fg = foreground;
      colors.tabs.selected.even.bg = background;
      colors.tabs.selected.even.fg = foreground;
      colors.tabs.selected.odd.bg = background;
      colors.tabs.selected.odd.fg = foreground;
      tabs.indicator.width = 1;
      tabs.favicons.scale = 1;
    };

  };
}
