syntax on
set clipboard=unnamedplus
set nowrap
set splitright
set omnifunc=ale#completion#OmniFunc
set t_Co=256
let g:airline_theme='dracula'
let g:ale_completion_enabled = 1
let g:ale_lint_on_text_changed = 1
let g:ale_fix_on_save = 1
let g:ale_completion_autoimport = 1
let g:ale_fixers = {
\ '*': [ 'remove_trailing_lines', 'trim_whitespace' ],
\ 'nix': [ 'nixfmt' ],
\ 'markdown': [ 'pandoc' ],
\ 'scala': [ 'scalafmt' ],
\ 'haskell': [ 'ormolu' ],
\ 'python': [ 'black', 'isort' ],
\ 'yaml': [ 'yamlfix' ],
\ 'javascript': [ 'prettier' ],
\ 'c': [ 'astyle' ],
\}
let g:ale_linters = {
\ 'nix': [ 'statix' ]
\}
let g:vimwiki_list = [
\ {
\ 'path': '/home/collin/vimwiki',
\ 'auto_toc': 1,
\ },
\ {
\ 'path': '/home/collin/projects/collinarnett.github.io/wiki',
\ 'path_html': '/home/collin/projects/collinarnett.github.io/docs',
\ 'auto_toc': 1,
\ 'exclude_files': [ '**/README.md' ],
\ 'auto_export': 1,
\ },
\ ]
let g:airline#extensions#ale#enabled = 1
let g:mkdp_browser = 'firefox'
highlight link CocErrorSign DraculaErrorLine
highlight link CocInfoSign DraculaInfoLine
autocmd FileType css setlocal tabstop=2 shiftwidth=2
autocmd FileType haskell setlocal tabstop=2 shiftwidth=2
autocmd FileType json setlocal tabstop=2 shiftwidth=2
autocmd FileType c setlocal tabstop=4 shiftwidth=4
autocmd FileType java setlocal tabstop=4 shiftwidth=4
autocmd FileType markdown setlocal spell
autocmd FileType markdown setlocal tabstop=2 shiftwidth=2
au BufRead,BufNewFile *.wiki setlocal textwidth=80 spell tabstop=2 shiftwidth=2
autocmd FileType xml setlocal tabstop=2 shiftwidth=2
autocmd FileType help wincmd L
autocmd FileType gitcommit setlocal spell
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
