-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Battery
module GrocyClient.Types.Battery where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified GrocyClient.Common
import GrocyClient.TypeAlias

-- | Defines the object schema located at @components.schemas.Battery@ in the specification.
-- 
-- 
data Battery = Battery {
  -- | charge_interval_days
  -- 
  -- Constraints:
  -- 
  -- * Minimum  of 0.0
  batteryCharge_interval_days :: (Maybe.Maybe GHC.Types.Int)
  -- | description
  , batteryDescription :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , batteryId :: (Maybe.Maybe GHC.Types.Int)
  -- | name
  , batteryName :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | row_created_timestamp
  , batteryRow_created_timestamp :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | used_in
  , batteryUsed_in :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | userfields: Key\/value pairs of userfields
  , batteryUserfields :: (Maybe.Maybe Data.Aeson.Types.Internal.Object)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Battery
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("charge_interval_days" Data.Aeson.Types.ToJSON..=)) (batteryCharge_interval_days obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("description" Data.Aeson.Types.ToJSON..=)) (batteryDescription obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("id" Data.Aeson.Types.ToJSON..=)) (batteryId obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("name" Data.Aeson.Types.ToJSON..=)) (batteryName obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("row_created_timestamp" Data.Aeson.Types.ToJSON..=)) (batteryRow_created_timestamp obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("used_in" Data.Aeson.Types.ToJSON..=)) (batteryUsed_in obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("userfields" Data.Aeson.Types.ToJSON..=)) (batteryUserfields obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("charge_interval_days" Data.Aeson.Types.ToJSON..=)) (batteryCharge_interval_days obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("description" Data.Aeson.Types.ToJSON..=)) (batteryDescription obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("id" Data.Aeson.Types.ToJSON..=)) (batteryId obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("name" Data.Aeson.Types.ToJSON..=)) (batteryName obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("row_created_timestamp" Data.Aeson.Types.ToJSON..=)) (batteryRow_created_timestamp obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("used_in" Data.Aeson.Types.ToJSON..=)) (batteryUsed_in obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("userfields" Data.Aeson.Types.ToJSON..=)) (batteryUserfields obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Battery
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Battery" (\obj -> ((((((Base.pure Battery Base.<*> (obj Data.Aeson.Types.FromJSON..:! "charge_interval_days")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "id")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "row_created_timestamp")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "used_in")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "userfields"))}
-- | Create a new 'Battery' with all required fields.
mkBattery :: Battery
mkBattery = Battery{batteryCharge_interval_days = Maybe.Nothing,
                    batteryDescription = Maybe.Nothing,
                    batteryId = Maybe.Nothing,
                    batteryName = Maybe.Nothing,
                    batteryRow_created_timestamp = Maybe.Nothing,
                    batteryUsed_in = Maybe.Nothing,
                    batteryUserfields = Maybe.Nothing}
