-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ChoreDetailsResponse
module GrocyClient.Types.ChoreDetailsResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified GrocyClient.Common
import GrocyClient.TypeAlias
import {-# SOURCE #-} GrocyClient.Types.Chore
import {-# SOURCE #-} GrocyClient.Types.UserDto

-- | Defines the object schema located at @components.schemas.ChoreDetailsResponse@ in the specification.
-- 
-- 
data ChoreDetailsResponse = ChoreDetailsResponse {
  -- | average_execution_frequency_hours: Contains the average past execution frequency in hours or \`null\`, when the chore was never executed before
  choreDetailsResponseAverage_execution_frequency_hours :: (Maybe.Maybe GHC.Types.Int)
  -- | chore
  , choreDetailsResponseChore :: (Maybe.Maybe Chore)
  -- | last_done_by: A user object without the *password* and with an additional *display_name* property
  , choreDetailsResponseLast_done_by :: (Maybe.Maybe UserDto)
  -- | last_tracked: When this chore was last tracked
  , choreDetailsResponseLast_tracked :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | next_estimated_execution_time
  , choreDetailsResponseNext_estimated_execution_time :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | next_execution_assigned_user: A user object without the *password* and with an additional *display_name* property
  , choreDetailsResponseNext_execution_assigned_user :: (Maybe.Maybe UserDto)
  -- | track_count: How often this chore was tracked so far
  , choreDetailsResponseTrack_count :: (Maybe.Maybe GHC.Types.Int)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ChoreDetailsResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("average_execution_frequency_hours" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseAverage_execution_frequency_hours obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("chore" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseChore obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("last_done_by" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseLast_done_by obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("last_tracked" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseLast_tracked obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("next_estimated_execution_time" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseNext_estimated_execution_time obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("next_execution_assigned_user" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseNext_execution_assigned_user obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("track_count" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseTrack_count obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("average_execution_frequency_hours" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseAverage_execution_frequency_hours obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("chore" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseChore obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("last_done_by" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseLast_done_by obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("last_tracked" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseLast_tracked obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("next_estimated_execution_time" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseNext_estimated_execution_time obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("next_execution_assigned_user" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseNext_execution_assigned_user obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("track_count" Data.Aeson.Types.ToJSON..=)) (choreDetailsResponseTrack_count obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ChoreDetailsResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ChoreDetailsResponse" (\obj -> ((((((Base.pure ChoreDetailsResponse Base.<*> (obj Data.Aeson.Types.FromJSON..:! "average_execution_frequency_hours")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "chore")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "last_done_by")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "last_tracked")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "next_estimated_execution_time")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "next_execution_assigned_user")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "track_count"))}
-- | Create a new 'ChoreDetailsResponse' with all required fields.
mkChoreDetailsResponse :: ChoreDetailsResponse
mkChoreDetailsResponse = ChoreDetailsResponse{choreDetailsResponseAverage_execution_frequency_hours = Maybe.Nothing,
                                              choreDetailsResponseChore = Maybe.Nothing,
                                              choreDetailsResponseLast_done_by = Maybe.Nothing,
                                              choreDetailsResponseLast_tracked = Maybe.Nothing,
                                              choreDetailsResponseNext_estimated_execution_time = Maybe.Nothing,
                                              choreDetailsResponseNext_execution_assigned_user = Maybe.Nothing,
                                              choreDetailsResponseTrack_count = Maybe.Nothing}
