-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Error400
module GrocyClient.Types.Error400 where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified GrocyClient.Common
import GrocyClient.TypeAlias

-- | Defines the object schema located at @components.schemas.Error400@ in the specification.
-- 
-- 
data Error400 = Error400 {
  -- | error_message
  error400Error_message :: (Maybe.Maybe Data.Text.Internal.Text)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Error400
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("error_message" Data.Aeson.Types.ToJSON..=)) (error400Error_message obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("error_message" Data.Aeson.Types.ToJSON..=)) (error400Error_message obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Error400
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Error400" (\obj -> Base.pure Error400 Base.<*> (obj Data.Aeson.Types.FromJSON..:! "error_message"))}
-- | Create a new 'Error400' with all required fields.
mkError400 :: Error400
mkError400 = Error400{error400Error_message = Maybe.Nothing}
