-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ExternalBarcodeLookupResponse
module GrocyClient.Types.ExternalBarcodeLookupResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified GrocyClient.Common
import GrocyClient.TypeAlias

-- | Defines the object schema located at @components.schemas.ExternalBarcodeLookupResponse@ in the specification.
-- 
-- 
data ExternalBarcodeLookupResponse = ExternalBarcodeLookupResponse {
  -- | barcode: Can contain multiple barcodes separated by comma
  externalBarcodeLookupResponseBarcode :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | id: The id of the added product, only included when the producted was added to the database
  , externalBarcodeLookupResponseId :: (Maybe.Maybe GHC.Types.Int)
  -- | location_id
  , externalBarcodeLookupResponseLocation_id :: (Maybe.Maybe GHC.Types.Int)
  -- | name
  , externalBarcodeLookupResponseName :: (Maybe.Maybe Data.Text.Internal.Text)
  -- | qu_factor_purchase_to_stock
  , externalBarcodeLookupResponseQu_factor_purchase_to_stock :: (Maybe.Maybe GHC.Types.Double)
  -- | qu_id_purchase
  , externalBarcodeLookupResponseQu_id_purchase :: (Maybe.Maybe GHC.Types.Int)
  -- | qu_id_stock
  , externalBarcodeLookupResponseQu_id_stock :: (Maybe.Maybe GHC.Types.Int)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ExternalBarcodeLookupResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("barcode" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseBarcode obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("id" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseId obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("location_id" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseLocation_id obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("name" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseName obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_factor_purchase_to_stock" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_factor_purchase_to_stock obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_id_purchase" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_id_purchase obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_id_stock" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_id_stock obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("barcode" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseBarcode obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("id" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseId obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("location_id" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseLocation_id obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("name" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseName obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_factor_purchase_to_stock" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_factor_purchase_to_stock obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_id_purchase" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_id_purchase obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("qu_id_stock" Data.Aeson.Types.ToJSON..=)) (externalBarcodeLookupResponseQu_id_stock obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ExternalBarcodeLookupResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ExternalBarcodeLookupResponse" (\obj -> ((((((Base.pure ExternalBarcodeLookupResponse Base.<*> (obj Data.Aeson.Types.FromJSON..:! "barcode")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "id")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "location_id")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "qu_factor_purchase_to_stock")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "qu_id_purchase")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "qu_id_stock"))}
-- | Create a new 'ExternalBarcodeLookupResponse' with all required fields.
mkExternalBarcodeLookupResponse :: ExternalBarcodeLookupResponse
mkExternalBarcodeLookupResponse = ExternalBarcodeLookupResponse{externalBarcodeLookupResponseBarcode = Maybe.Nothing,
                                                                externalBarcodeLookupResponseId = Maybe.Nothing,
                                                                externalBarcodeLookupResponseLocation_id = Maybe.Nothing,
                                                                externalBarcodeLookupResponseName = Maybe.Nothing,
                                                                externalBarcodeLookupResponseQu_factor_purchase_to_stock = Maybe.Nothing,
                                                                externalBarcodeLookupResponseQu_id_purchase = Maybe.Nothing,
                                                                externalBarcodeLookupResponseQu_id_stock = Maybe.Nothing}
