-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema RecipeFulfillmentResponse
module GrocyClient.Types.RecipeFulfillmentResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified GrocyClient.Common
import GrocyClient.TypeAlias

-- | Defines the object schema located at @components.schemas.RecipeFulfillmentResponse@ in the specification.
-- 
-- 
data RecipeFulfillmentResponse = RecipeFulfillmentResponse {
  -- | costs
  recipeFulfillmentResponseCosts :: (Maybe.Maybe GHC.Types.Double)
  -- | missing_products_count
  , recipeFulfillmentResponseMissing_products_count :: (Maybe.Maybe GHC.Types.Int)
  -- | need_fulfilled
  , recipeFulfillmentResponseNeed_fulfilled :: (Maybe.Maybe GHC.Types.Bool)
  -- | need_fulfilled_with_shopping_list
  , recipeFulfillmentResponseNeed_fulfilled_with_shopping_list :: (Maybe.Maybe GHC.Types.Bool)
  -- | recipe_id
  , recipeFulfillmentResponseRecipe_id :: (Maybe.Maybe GHC.Types.Int)
  } deriving (Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON RecipeFulfillmentResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("costs" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseCosts obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("missing_products_count" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseMissing_products_count obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("need_fulfilled" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseNeed_fulfilled obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("need_fulfilled_with_shopping_list" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseNeed_fulfilled_with_shopping_list obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("recipe_id" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseRecipe_id obj) : Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe Base.mempty (Base.pure Base.. ("costs" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseCosts obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("missing_products_count" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseMissing_products_count obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("need_fulfilled" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseNeed_fulfilled obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("need_fulfilled_with_shopping_list" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseNeed_fulfilled_with_shopping_list obj) : Data.Maybe.maybe Base.mempty (Base.pure Base.. ("recipe_id" Data.Aeson.Types.ToJSON..=)) (recipeFulfillmentResponseRecipe_id obj) : Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON RecipeFulfillmentResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "RecipeFulfillmentResponse" (\obj -> ((((Base.pure RecipeFulfillmentResponse Base.<*> (obj Data.Aeson.Types.FromJSON..:! "costs")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "missing_products_count")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "need_fulfilled")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "need_fulfilled_with_shopping_list")) Base.<*> (obj Data.Aeson.Types.FromJSON..:! "recipe_id"))}
-- | Create a new 'RecipeFulfillmentResponse' with all required fields.
mkRecipeFulfillmentResponse :: RecipeFulfillmentResponse
mkRecipeFulfillmentResponse = RecipeFulfillmentResponse{recipeFulfillmentResponseCosts = Maybe.Nothing,
                                                        recipeFulfillmentResponseMissing_products_count = Maybe.Nothing,
                                                        recipeFulfillmentResponseNeed_fulfilled = Maybe.Nothing,
                                                        recipeFulfillmentResponseNeed_fulfilled_with_shopping_list = Maybe.Nothing,
                                                        recipeFulfillmentResponseRecipe_id = Maybe.Nothing}
